---
title: "Podsumowanie"
---

Przeprowadzona analiza wskazuje na istotny wpływ programów rządowych na poparcie PiS, aczkolwiek są to czynniki drugorzędne. Najważniejszym czynnikiem wpływającym na poparcie PiS okazał się stopień konserwatyzmu danego powiatu. W modelu objaśniającym wzrost poparcia dla partii rządzącej najistotniejszy okazał się wynik jaki uzyskał PSL w 2015 r. Zmiennymi o relatywnie niewielkim wpływie na wyniki wyborów okazały się zmienne gospodarcze takie jak poziom bezrobocia oraz średnia płaca.

Uzyskane wyniki sugerują że pomimo wydania ponad 30 mld złotych na główne punkty programu wyborczego PiS, ważniejsza okazała się wojna światopoglądowa prowadzona między obozem rządzącym, a opozycją. Tę batalię zdaje się wygrywać PiS. Co więcej, można nawet wysnuć śmiałą tezę, że domniemany efekt *Sekielskiego* miał rzeczywiście wpływ na wynik wyborów, ale przeciwny do zakładanego przez media opozycyjne. Jednocześnie można domniemywać, że na obecności PSL w Koalicji Eurpojskiej najbardziej zyskał PiS.
